version: "3.9" 

services:

  postgres: 
    container_name: postgres
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes: 
      - pgdata:/var/lib/postgresql/data/ 
    ports: 
      - "5432:5432" 
    networks: 
      - keycloak-network
    

  pgadmin: 
    container_name: pgadmin 
    image: "dpage/pgadmin4:latest"
    restart: always
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - "5050:80"
    networks: 
      - keycloak-network
#apparently this is to define an alias for the database host name
#    links:
#      - "postgres:postgres"


  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:latest"
    depends_on: 
      - "postgres" 
    environment:

#      this is NOT the admin password I don't know why it's not working
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_ADMIN_REALM: master
#      this is the one that should be used
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgrespw
#      TZ: Europe/Rome

    ports: 
      - "127.0.0.1:8180:8080" 
      - "127.0.0.1:8787:8787" # debug port 
    networks: 
      - keycloak-network


networks:
  keycloak-network:

volumes:
  pgdata:
